#!/bin/bash

### Tool and package installations

echo "Installing brew..."
if ! command -v "brew" >/dev/null 2>&1; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
	echo "brew is already installed!"
fi

declare -a brew_formulae=("git" "gh" "starship" "pyenv")
declare -a installed=()
declare -a skipped=()

for i in "${brew_formulae[@]}"; do
    if ! command -v "$i" >/dev/null 2>&1; then
        brew install "$i"
        installed+=("$i")
    else
        skipped+=("$i")
    fi
done

if (( "${#installed[@]}" == 0 )); then
	echo "All brew formulae are already installed!"
else
	echo "Installed ${#installed[@]} of ${#brew_formulae[@]} formulae via brew."
	for i in "${installed[@]}"; do printf '  %-20s\n'        "$i"; done
	for i in "${skipped[@]}";   do printf '  %-20s(skipped)\n' "$i"; done
fi

echo "Installing nvm..."
if ! command -v "$NVM_DIR/nvm.sh" >/dev/null 2>&1; then
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
else
	echo "nvm is already installed!"
fi

echo "Installing Ghostty..."
ls /Applications | grep -q Ghostty.app
if [ $? -ne 0 ]; then
    brew install --cask ghostty
else
	echo "Ghostty already installed!"
fi

### Package configuration

mkdir -p ~/.config

# ghostty config
cp "$HOME/Templates/config.ghostty" "$HOME/.config/ghostty"
echo "✓ Copied config.ghostty to $HOME/.config/ghostty/config.ghostty"

# starship config
cp "$HOME/Templates/starship.toml" "$HOME/.config"
echo "✓ Copied starship.toml to $HOME/.config/starship.toml"

### Shell configuration

shell_cfg="$HOME/.zshrc"
if ! [ -e "$shell_cfg" ] ; then
    touch "$shell_cfg"
fi

# Add Scripts directory to the PATH
echo $PATH | grep -q "$HOME/Scripts"

if [ $? -ne 0 ]; then
    echo -e 'PATH="$HOME/Scripts:$PATH"\n' >> "$shell_cfg"
	echo "✓ Scripts added to PATH"
fi

# starship init
starship_init='eval "$(starship init zsh)"'
grep -q "$starship_init" "$shell_cfg"

if [ $? -ne 0 ]; then
    echo -e "$starship_init\n" >> "$shell_cfg"
	echo "✓ starship init added to $shell_cfg"
fi

# pyenv init
read -r -d '' pyenv_init <<- EOT
	# pyenv to path
	PYENV_ROOT="\$HOME/.pyenv"
	[[ -d \$PYENV_ROOT/bin ]] && PATH="\$PYENV_ROOT/bin:\$PATH"
	eval "\$(pyenv init -)"
EOT
grep -q "$pyenv_init" "$shell_cfg"

if [ $? -ne 0 ]; then
    echo -e "$pyenv_init\n" >> "$shell_cfg"
	echo "✓ pyenv init added to $shell_cfg"
else
	echo "✓ pyenv already initialised"
fi

# nvm init
read -r -d '' nvm_init <<- EOT
	export NVM_DIR="\$HOME/.nvm"
	[ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"  # This loads nvm
	[ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion
EOT
grep -q "$nvm_init" "$shell_cfg"

if [ $? -ne 0 ]; then
    echo -e "$nvm_init\n" >> "$shell_cfg"
	echo "✓ nvm init added to $shell_cfg"
else
	echo "✓ nvm already initialised"
fi

### Final steps

echo -e "\nAll done, go crazy."
