#!/bin/bash

### Tool and package installations

echo "Installing brew..."
if ! command -v "brew" >/dev/null 2>&1; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
else
	echo "brew is already installed!"
fi

declare -a brew_formulae=("git" "gh" "starship" "fzf" "pyenv")
declare -a installed=()
declare -a skipped=()

for i in "${brew_formulae[@]}"; do
    if ! command -v "$i" >/dev/null 2>&1; then
        brew install "$i"
        installed+=("$i")
    else
        skipped+=("$i")
    fi
done

if (( "${#installed[@]}" == 0 )); then
	echo "All brew formulae are already installed!"
else
	echo "Installed ${#installed[@]} of ${#brew_formulae[@]} formulae via brew."
	for i in "${installed[@]}"; do printf '  %-20s\n'        "$i"; done
	for i in "${skipped[@]}";   do printf '  %-20s(skipped)\n' "$i"; done
fi

echo "Installing nvm..."
if ! command -v "$NVM_DIR/nvm.sh" >/dev/null 2>&1; then
	curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
else
	echo "nvm is already installed!"
fi

echo "Installing Ghostty..."
ls /Applications | grep -q Ghostty.app
if [ $? -ne 0 ]; then
    brew install --cask ghostty
else
	echo "Ghostty already installed!"
fi

### Package configuration

mkdir -p ~/.config

# ghostty config
cp "$HOME/Templates/config.ghostty" "$HOME/.config/ghostty"
echo "✓ Copied config.ghostty to $HOME/.config/ghostty/config.ghostty"

# starship config
cp "$HOME/Templates/starship.toml" "$HOME/.config"
echo "✓ Copied starship.toml to $HOME/.config/starship.toml"

### Run shell configuration program
go run "$HOME/Scripts/cmd/configure_zshrc/main.go -append -d"

### Final steps

echo -e "\nAll done, go crazy."
